FROM centos:7
LABEL maintainer "Andrei Poenaru <docker@simd.stream>"

RUN yum install -y \
    autoconf \
    automake \
    byacc \
    bzip2-devel \
    cmake \
    curl \
    gcc \
    gcc-c++ \
    git \
    glib2-devel \
    glibc-static \
    ImageMagick-devel \
    kernel-devel \
    libcurl-devel \
    libevent-devel \
    libevent-devel \
    libffi-devel \
    libjpeg-devel \
    libstdc++-static \
    libxml2-devel \
    libxslt-devel \
    libyaml-devel \
    make \
    mysql-devel \
    ncurses-devel \
    ncurses-devel \
    openssl \
    openssl-devel \
    openssl-devel \
    postgresql-devel \
    readline \
    readline-devel \
    sqlite-devel \
    wget \
    which \
    zlib-devel \
    && yum clean all

